/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payload.proto

package org.opensearch.opnipreprocessing.plugin;

public final class OpniPayloadProto {
  private OpniPayloadProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:loganomaly.Payload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string _id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string _id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string cluster_id = 2;</code>
     * @return The clusterId.
     */
    java.lang.String getClusterId();
    /**
     * <code>string cluster_id = 2;</code>
     * @return The bytes for clusterId.
     */
    com.google.protobuf.ByteString
        getClusterIdBytes();

    /**
     * <code>string log = 3;</code>
     * @return The log.
     */
    java.lang.String getLog();
    /**
     * <code>string log = 3;</code>
     * @return The bytes for log.
     */
    com.google.protobuf.ByteString
        getLogBytes();

    /**
     * <code>string masked_log = 4;</code>
     * @return The maskedLog.
     */
    java.lang.String getMaskedLog();
    /**
     * <code>string masked_log = 4;</code>
     * @return The bytes for maskedLog.
     */
    com.google.protobuf.ByteString
        getMaskedLogBytes();

    /**
     * <code>string anomaly_level = 5;</code>
     * @return The anomalyLevel.
     */
    java.lang.String getAnomalyLevel();
    /**
     * <code>string anomaly_level = 5;</code>
     * @return The bytes for anomalyLevel.
     */
    com.google.protobuf.ByteString
        getAnomalyLevelBytes();

    /**
     * <code>string log_type = 6;</code>
     * @return The logType.
     */
    java.lang.String getLogType();
    /**
     * <code>string log_type = 6;</code>
     * @return The bytes for logType.
     */
    com.google.protobuf.ByteString
        getLogTypeBytes();

    /**
     * <code>string drain_pretrained_template_matched = 7;</code>
     * @return The drainPretrainedTemplateMatched.
     */
    java.lang.String getDrainPretrainedTemplateMatched();
    /**
     * <code>string drain_pretrained_template_matched = 7;</code>
     * @return The bytes for drainPretrainedTemplateMatched.
     */
    com.google.protobuf.ByteString
        getDrainPretrainedTemplateMatchedBytes();

    /**
     * <code>string inference_model = 8;</code>
     * @return The inferenceModel.
     */
    java.lang.String getInferenceModel();
    /**
     * <code>string inference_model = 8;</code>
     * @return The bytes for inferenceModel.
     */
    com.google.protobuf.ByteString
        getInferenceModelBytes();

    /**
     * <code>float opnilog_confidence = 9;</code>
     * @return The opnilogConfidence.
     */
    float getOpnilogConfidence();
  }
  /**
   * Protobuf type {@code loganomaly.Payload}
   */
  public static final class Payload extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:loganomaly.Payload)
      PayloadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Payload.newBuilder() to construct.
    private Payload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Payload() {
      Id_ = "";
      clusterId_ = "";
      log_ = "";
      maskedLog_ = "";
      anomalyLevel_ = "";
      logType_ = "";
      drainPretrainedTemplateMatched_ = "";
      inferenceModel_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Payload();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Payload(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              Id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              clusterId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              log_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              maskedLog_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              anomalyLevel_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              logType_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              drainPretrainedTemplateMatched_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              inferenceModel_ = s;
              break;
            }
            case 77: {

              opnilogConfidence_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.internal_static_loganomaly_Payload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.internal_static_loganomaly_Payload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload.class, org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload.Builder.class);
    }

    public static final int _ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object Id_;
    /**
     * <code>string _id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = Id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        Id_ = s;
        return s;
      }
    }
    /**
     * <code>string _id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = Id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        Id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLUSTER_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object clusterId_;
    /**
     * <code>string cluster_id = 2;</code>
     * @return The clusterId.
     */
    @java.lang.Override
    public java.lang.String getClusterId() {
      java.lang.Object ref = clusterId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clusterId_ = s;
        return s;
      }
    }
    /**
     * <code>string cluster_id = 2;</code>
     * @return The bytes for clusterId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClusterIdBytes() {
      java.lang.Object ref = clusterId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clusterId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOG_FIELD_NUMBER = 3;
    private volatile java.lang.Object log_;
    /**
     * <code>string log = 3;</code>
     * @return The log.
     */
    @java.lang.Override
    public java.lang.String getLog() {
      java.lang.Object ref = log_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        log_ = s;
        return s;
      }
    }
    /**
     * <code>string log = 3;</code>
     * @return The bytes for log.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLogBytes() {
      java.lang.Object ref = log_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        log_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MASKED_LOG_FIELD_NUMBER = 4;
    private volatile java.lang.Object maskedLog_;
    /**
     * <code>string masked_log = 4;</code>
     * @return The maskedLog.
     */
    @java.lang.Override
    public java.lang.String getMaskedLog() {
      java.lang.Object ref = maskedLog_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        maskedLog_ = s;
        return s;
      }
    }
    /**
     * <code>string masked_log = 4;</code>
     * @return The bytes for maskedLog.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMaskedLogBytes() {
      java.lang.Object ref = maskedLog_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        maskedLog_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ANOMALY_LEVEL_FIELD_NUMBER = 5;
    private volatile java.lang.Object anomalyLevel_;
    /**
     * <code>string anomaly_level = 5;</code>
     * @return The anomalyLevel.
     */
    @java.lang.Override
    public java.lang.String getAnomalyLevel() {
      java.lang.Object ref = anomalyLevel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        anomalyLevel_ = s;
        return s;
      }
    }
    /**
     * <code>string anomaly_level = 5;</code>
     * @return The bytes for anomalyLevel.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAnomalyLevelBytes() {
      java.lang.Object ref = anomalyLevel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        anomalyLevel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOG_TYPE_FIELD_NUMBER = 6;
    private volatile java.lang.Object logType_;
    /**
     * <code>string log_type = 6;</code>
     * @return The logType.
     */
    @java.lang.Override
    public java.lang.String getLogType() {
      java.lang.Object ref = logType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        logType_ = s;
        return s;
      }
    }
    /**
     * <code>string log_type = 6;</code>
     * @return The bytes for logType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLogTypeBytes() {
      java.lang.Object ref = logType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DRAIN_PRETRAINED_TEMPLATE_MATCHED_FIELD_NUMBER = 7;
    private volatile java.lang.Object drainPretrainedTemplateMatched_;
    /**
     * <code>string drain_pretrained_template_matched = 7;</code>
     * @return The drainPretrainedTemplateMatched.
     */
    @java.lang.Override
    public java.lang.String getDrainPretrainedTemplateMatched() {
      java.lang.Object ref = drainPretrainedTemplateMatched_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        drainPretrainedTemplateMatched_ = s;
        return s;
      }
    }
    /**
     * <code>string drain_pretrained_template_matched = 7;</code>
     * @return The bytes for drainPretrainedTemplateMatched.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDrainPretrainedTemplateMatchedBytes() {
      java.lang.Object ref = drainPretrainedTemplateMatched_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        drainPretrainedTemplateMatched_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INFERENCE_MODEL_FIELD_NUMBER = 8;
    private volatile java.lang.Object inferenceModel_;
    /**
     * <code>string inference_model = 8;</code>
     * @return The inferenceModel.
     */
    @java.lang.Override
    public java.lang.String getInferenceModel() {
      java.lang.Object ref = inferenceModel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        inferenceModel_ = s;
        return s;
      }
    }
    /**
     * <code>string inference_model = 8;</code>
     * @return The bytes for inferenceModel.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInferenceModelBytes() {
      java.lang.Object ref = inferenceModel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        inferenceModel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPNILOG_CONFIDENCE_FIELD_NUMBER = 9;
    private float opnilogConfidence_;
    /**
     * <code>float opnilog_confidence = 9;</code>
     * @return The opnilogConfidence.
     */
    @java.lang.Override
    public float getOpnilogConfidence() {
      return opnilogConfidence_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(Id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, Id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clusterId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clusterId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(log_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, log_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(maskedLog_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, maskedLog_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(anomalyLevel_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, anomalyLevel_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(logType_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, logType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(drainPretrainedTemplateMatched_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, drainPretrainedTemplateMatched_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(inferenceModel_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, inferenceModel_);
      }
      if (java.lang.Float.floatToRawIntBits(opnilogConfidence_) != 0) {
        output.writeFloat(9, opnilogConfidence_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(Id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, Id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clusterId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clusterId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(log_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, log_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(maskedLog_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, maskedLog_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(anomalyLevel_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, anomalyLevel_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(logType_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, logType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(drainPretrainedTemplateMatched_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, drainPretrainedTemplateMatched_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(inferenceModel_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, inferenceModel_);
      }
      if (java.lang.Float.floatToRawIntBits(opnilogConfidence_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(9, opnilogConfidence_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload)) {
        return super.equals(obj);
      }
      org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload other = (org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getClusterId()
          .equals(other.getClusterId())) return false;
      if (!getLog()
          .equals(other.getLog())) return false;
      if (!getMaskedLog()
          .equals(other.getMaskedLog())) return false;
      if (!getAnomalyLevel()
          .equals(other.getAnomalyLevel())) return false;
      if (!getLogType()
          .equals(other.getLogType())) return false;
      if (!getDrainPretrainedTemplateMatched()
          .equals(other.getDrainPretrainedTemplateMatched())) return false;
      if (!getInferenceModel()
          .equals(other.getInferenceModel())) return false;
      if (java.lang.Float.floatToIntBits(getOpnilogConfidence())
          != java.lang.Float.floatToIntBits(
              other.getOpnilogConfidence())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + _ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + CLUSTER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getClusterId().hashCode();
      hash = (37 * hash) + LOG_FIELD_NUMBER;
      hash = (53 * hash) + getLog().hashCode();
      hash = (37 * hash) + MASKED_LOG_FIELD_NUMBER;
      hash = (53 * hash) + getMaskedLog().hashCode();
      hash = (37 * hash) + ANOMALY_LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getAnomalyLevel().hashCode();
      hash = (37 * hash) + LOG_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getLogType().hashCode();
      hash = (37 * hash) + DRAIN_PRETRAINED_TEMPLATE_MATCHED_FIELD_NUMBER;
      hash = (53 * hash) + getDrainPretrainedTemplateMatched().hashCode();
      hash = (37 * hash) + INFERENCE_MODEL_FIELD_NUMBER;
      hash = (53 * hash) + getInferenceModel().hashCode();
      hash = (37 * hash) + OPNILOG_CONFIDENCE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getOpnilogConfidence());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code loganomaly.Payload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:loganomaly.Payload)
        org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.internal_static_loganomaly_Payload_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.internal_static_loganomaly_Payload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload.class, org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload.Builder.class);
      }

      // Construct using org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        Id_ = "";

        clusterId_ = "";

        log_ = "";

        maskedLog_ = "";

        anomalyLevel_ = "";

        logType_ = "";

        drainPretrainedTemplateMatched_ = "";

        inferenceModel_ = "";

        opnilogConfidence_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.internal_static_loganomaly_Payload_descriptor;
      }

      @java.lang.Override
      public org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload getDefaultInstanceForType() {
        return org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload.getDefaultInstance();
      }

      @java.lang.Override
      public org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload build() {
        org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload buildPartial() {
        org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload result = new org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload(this);
        result.Id_ = Id_;
        result.clusterId_ = clusterId_;
        result.log_ = log_;
        result.maskedLog_ = maskedLog_;
        result.anomalyLevel_ = anomalyLevel_;
        result.logType_ = logType_;
        result.drainPretrainedTemplateMatched_ = drainPretrainedTemplateMatched_;
        result.inferenceModel_ = inferenceModel_;
        result.opnilogConfidence_ = opnilogConfidence_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload) {
          return mergeFrom((org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload other) {
        if (other == org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          Id_ = other.Id_;
          onChanged();
        }
        if (!other.getClusterId().isEmpty()) {
          clusterId_ = other.clusterId_;
          onChanged();
        }
        if (!other.getLog().isEmpty()) {
          log_ = other.log_;
          onChanged();
        }
        if (!other.getMaskedLog().isEmpty()) {
          maskedLog_ = other.maskedLog_;
          onChanged();
        }
        if (!other.getAnomalyLevel().isEmpty()) {
          anomalyLevel_ = other.anomalyLevel_;
          onChanged();
        }
        if (!other.getLogType().isEmpty()) {
          logType_ = other.logType_;
          onChanged();
        }
        if (!other.getDrainPretrainedTemplateMatched().isEmpty()) {
          drainPretrainedTemplateMatched_ = other.drainPretrainedTemplateMatched_;
          onChanged();
        }
        if (!other.getInferenceModel().isEmpty()) {
          inferenceModel_ = other.inferenceModel_;
          onChanged();
        }
        if (other.getOpnilogConfidence() != 0F) {
          setOpnilogConfidence(other.getOpnilogConfidence());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object Id_ = "";
      /**
       * <code>string _id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = Id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          Id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string _id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = Id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          Id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string _id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        Id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string _id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        Id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string _id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        Id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clusterId_ = "";
      /**
       * <code>string cluster_id = 2;</code>
       * @return The clusterId.
       */
      public java.lang.String getClusterId() {
        java.lang.Object ref = clusterId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clusterId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cluster_id = 2;</code>
       * @return The bytes for clusterId.
       */
      public com.google.protobuf.ByteString
          getClusterIdBytes() {
        java.lang.Object ref = clusterId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clusterId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cluster_id = 2;</code>
       * @param value The clusterId to set.
       * @return This builder for chaining.
       */
      public Builder setClusterId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clusterId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cluster_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearClusterId() {
        
        clusterId_ = getDefaultInstance().getClusterId();
        onChanged();
        return this;
      }
      /**
       * <code>string cluster_id = 2;</code>
       * @param value The bytes for clusterId to set.
       * @return This builder for chaining.
       */
      public Builder setClusterIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clusterId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object log_ = "";
      /**
       * <code>string log = 3;</code>
       * @return The log.
       */
      public java.lang.String getLog() {
        java.lang.Object ref = log_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          log_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string log = 3;</code>
       * @return The bytes for log.
       */
      public com.google.protobuf.ByteString
          getLogBytes() {
        java.lang.Object ref = log_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          log_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string log = 3;</code>
       * @param value The log to set.
       * @return This builder for chaining.
       */
      public Builder setLog(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        log_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string log = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLog() {
        
        log_ = getDefaultInstance().getLog();
        onChanged();
        return this;
      }
      /**
       * <code>string log = 3;</code>
       * @param value The bytes for log to set.
       * @return This builder for chaining.
       */
      public Builder setLogBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        log_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object maskedLog_ = "";
      /**
       * <code>string masked_log = 4;</code>
       * @return The maskedLog.
       */
      public java.lang.String getMaskedLog() {
        java.lang.Object ref = maskedLog_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          maskedLog_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string masked_log = 4;</code>
       * @return The bytes for maskedLog.
       */
      public com.google.protobuf.ByteString
          getMaskedLogBytes() {
        java.lang.Object ref = maskedLog_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          maskedLog_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string masked_log = 4;</code>
       * @param value The maskedLog to set.
       * @return This builder for chaining.
       */
      public Builder setMaskedLog(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        maskedLog_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string masked_log = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaskedLog() {
        
        maskedLog_ = getDefaultInstance().getMaskedLog();
        onChanged();
        return this;
      }
      /**
       * <code>string masked_log = 4;</code>
       * @param value The bytes for maskedLog to set.
       * @return This builder for chaining.
       */
      public Builder setMaskedLogBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        maskedLog_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object anomalyLevel_ = "";
      /**
       * <code>string anomaly_level = 5;</code>
       * @return The anomalyLevel.
       */
      public java.lang.String getAnomalyLevel() {
        java.lang.Object ref = anomalyLevel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          anomalyLevel_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string anomaly_level = 5;</code>
       * @return The bytes for anomalyLevel.
       */
      public com.google.protobuf.ByteString
          getAnomalyLevelBytes() {
        java.lang.Object ref = anomalyLevel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          anomalyLevel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string anomaly_level = 5;</code>
       * @param value The anomalyLevel to set.
       * @return This builder for chaining.
       */
      public Builder setAnomalyLevel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        anomalyLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string anomaly_level = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAnomalyLevel() {
        
        anomalyLevel_ = getDefaultInstance().getAnomalyLevel();
        onChanged();
        return this;
      }
      /**
       * <code>string anomaly_level = 5;</code>
       * @param value The bytes for anomalyLevel to set.
       * @return This builder for chaining.
       */
      public Builder setAnomalyLevelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        anomalyLevel_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object logType_ = "";
      /**
       * <code>string log_type = 6;</code>
       * @return The logType.
       */
      public java.lang.String getLogType() {
        java.lang.Object ref = logType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          logType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string log_type = 6;</code>
       * @return The bytes for logType.
       */
      public com.google.protobuf.ByteString
          getLogTypeBytes() {
        java.lang.Object ref = logType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          logType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string log_type = 6;</code>
       * @param value The logType to set.
       * @return This builder for chaining.
       */
      public Builder setLogType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        logType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string log_type = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearLogType() {
        
        logType_ = getDefaultInstance().getLogType();
        onChanged();
        return this;
      }
      /**
       * <code>string log_type = 6;</code>
       * @param value The bytes for logType to set.
       * @return This builder for chaining.
       */
      public Builder setLogTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        logType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object drainPretrainedTemplateMatched_ = "";
      /**
       * <code>string drain_pretrained_template_matched = 7;</code>
       * @return The drainPretrainedTemplateMatched.
       */
      public java.lang.String getDrainPretrainedTemplateMatched() {
        java.lang.Object ref = drainPretrainedTemplateMatched_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          drainPretrainedTemplateMatched_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string drain_pretrained_template_matched = 7;</code>
       * @return The bytes for drainPretrainedTemplateMatched.
       */
      public com.google.protobuf.ByteString
          getDrainPretrainedTemplateMatchedBytes() {
        java.lang.Object ref = drainPretrainedTemplateMatched_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          drainPretrainedTemplateMatched_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string drain_pretrained_template_matched = 7;</code>
       * @param value The drainPretrainedTemplateMatched to set.
       * @return This builder for chaining.
       */
      public Builder setDrainPretrainedTemplateMatched(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        drainPretrainedTemplateMatched_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string drain_pretrained_template_matched = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearDrainPretrainedTemplateMatched() {
        
        drainPretrainedTemplateMatched_ = getDefaultInstance().getDrainPretrainedTemplateMatched();
        onChanged();
        return this;
      }
      /**
       * <code>string drain_pretrained_template_matched = 7;</code>
       * @param value The bytes for drainPretrainedTemplateMatched to set.
       * @return This builder for chaining.
       */
      public Builder setDrainPretrainedTemplateMatchedBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        drainPretrainedTemplateMatched_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object inferenceModel_ = "";
      /**
       * <code>string inference_model = 8;</code>
       * @return The inferenceModel.
       */
      public java.lang.String getInferenceModel() {
        java.lang.Object ref = inferenceModel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          inferenceModel_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string inference_model = 8;</code>
       * @return The bytes for inferenceModel.
       */
      public com.google.protobuf.ByteString
          getInferenceModelBytes() {
        java.lang.Object ref = inferenceModel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          inferenceModel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string inference_model = 8;</code>
       * @param value The inferenceModel to set.
       * @return This builder for chaining.
       */
      public Builder setInferenceModel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        inferenceModel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string inference_model = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearInferenceModel() {
        
        inferenceModel_ = getDefaultInstance().getInferenceModel();
        onChanged();
        return this;
      }
      /**
       * <code>string inference_model = 8;</code>
       * @param value The bytes for inferenceModel to set.
       * @return This builder for chaining.
       */
      public Builder setInferenceModelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        inferenceModel_ = value;
        onChanged();
        return this;
      }

      private float opnilogConfidence_ ;
      /**
       * <code>float opnilog_confidence = 9;</code>
       * @return The opnilogConfidence.
       */
      @java.lang.Override
      public float getOpnilogConfidence() {
        return opnilogConfidence_;
      }
      /**
       * <code>float opnilog_confidence = 9;</code>
       * @param value The opnilogConfidence to set.
       * @return This builder for chaining.
       */
      public Builder setOpnilogConfidence(float value) {
        
        opnilogConfidence_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float opnilog_confidence = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearOpnilogConfidence() {
        
        opnilogConfidence_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:loganomaly.Payload)
    }

    // @@protoc_insertion_point(class_scope:loganomaly.Payload)
    private static final org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload();
    }

    public static org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Payload>
        PARSER = new com.google.protobuf.AbstractParser<Payload>() {
      @java.lang.Override
      public Payload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Payload(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Payload> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Payload> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PayloadListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:loganomaly.PayloadList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .loganomaly.Payload items = 1;</code>
     */
    java.util.List<org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload> 
        getItemsList();
    /**
     * <code>repeated .loganomaly.Payload items = 1;</code>
     */
    org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload getItems(int index);
    /**
     * <code>repeated .loganomaly.Payload items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .loganomaly.Payload items = 1;</code>
     */
    java.util.List<? extends org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .loganomaly.Payload items = 1;</code>
     */
    org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code loganomaly.PayloadList}
   */
  public static final class PayloadList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:loganomaly.PayloadList)
      PayloadListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PayloadList.newBuilder() to construct.
    private PayloadList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PayloadList() {
      items_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PayloadList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PayloadList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                items_ = new java.util.ArrayList<org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload>();
                mutable_bitField0_ |= 0x00000001;
              }
              items_.add(
                  input.readMessage(org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.internal_static_loganomaly_PayloadList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.internal_static_loganomaly_PayloadList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList.class, org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList.Builder.class);
    }

    public static final int ITEMS_FIELD_NUMBER = 1;
    private java.util.List<org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload> items_;
    /**
     * <code>repeated .loganomaly.Payload items = 1;</code>
     */
    @java.lang.Override
    public java.util.List<org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .loganomaly.Payload items = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .loganomaly.Payload items = 1;</code>
     */
    @java.lang.Override
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .loganomaly.Payload items = 1;</code>
     */
    @java.lang.Override
    public org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .loganomaly.Payload items = 1;</code>
     */
    @java.lang.Override
    public org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(1, items_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, items_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList)) {
        return super.equals(obj);
      }
      org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList other = (org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList) obj;

      if (!getItemsList()
          .equals(other.getItemsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code loganomaly.PayloadList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:loganomaly.PayloadList)
        org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.internal_static_loganomaly_PayloadList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.internal_static_loganomaly_PayloadList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList.class, org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList.Builder.class);
      }

      // Construct using org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.internal_static_loganomaly_PayloadList_descriptor;
      }

      @java.lang.Override
      public org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList getDefaultInstanceForType() {
        return org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList.getDefaultInstance();
      }

      @java.lang.Override
      public org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList build() {
        org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList buildPartial() {
        org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList result = new org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList(this);
        int from_bitField0_ = bitField0_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList) {
          return mergeFrom((org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList other) {
        if (other == org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList.getDefaultInstance()) return this;
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          items_ = new java.util.ArrayList<org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload, org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload.Builder, org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .loganomaly.Payload items = 1;</code>
       */
      public java.util.List<org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .loganomaly.Payload items = 1;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .loganomaly.Payload items = 1;</code>
       */
      public org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .loganomaly.Payload items = 1;</code>
       */
      public Builder setItems(
          int index, org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .loganomaly.Payload items = 1;</code>
       */
      public Builder setItems(
          int index, org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .loganomaly.Payload items = 1;</code>
       */
      public Builder addItems(org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .loganomaly.Payload items = 1;</code>
       */
      public Builder addItems(
          int index, org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .loganomaly.Payload items = 1;</code>
       */
      public Builder addItems(
          org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .loganomaly.Payload items = 1;</code>
       */
      public Builder addItems(
          int index, org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .loganomaly.Payload items = 1;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .loganomaly.Payload items = 1;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .loganomaly.Payload items = 1;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .loganomaly.Payload items = 1;</code>
       */
      public org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .loganomaly.Payload items = 1;</code>
       */
      public org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .loganomaly.Payload items = 1;</code>
       */
      public java.util.List<? extends org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .loganomaly.Payload items = 1;</code>
       */
      public org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload.getDefaultInstance());
      }
      /**
       * <code>repeated .loganomaly.Payload items = 1;</code>
       */
      public org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload.getDefaultInstance());
      }
      /**
       * <code>repeated .loganomaly.Payload items = 1;</code>
       */
      public java.util.List<org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload, org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload.Builder, org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload, org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.Payload.Builder, org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:loganomaly.PayloadList)
    }

    // @@protoc_insertion_point(class_scope:loganomaly.PayloadList)
    private static final org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList();
    }

    public static org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PayloadList>
        PARSER = new com.google.protobuf.AbstractParser<PayloadList>() {
      @java.lang.Override
      public PayloadList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PayloadList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PayloadList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PayloadList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.opensearch.opnipreprocessing.plugin.OpniPayloadProto.PayloadList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_loganomaly_Payload_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_loganomaly_Payload_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_loganomaly_PayloadList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_loganomaly_PayloadList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpayload.proto\022\nloganomaly\"\324\001\n\007Payload\022" +
      "\013\n\003_id\030\001 \001(\t\022\022\n\ncluster_id\030\002 \001(\t\022\013\n\003log\030" +
      "\003 \001(\t\022\022\n\nmasked_log\030\004 \001(\t\022\025\n\ranomaly_lev" +
      "el\030\005 \001(\t\022\020\n\010log_type\030\006 \001(\t\022)\n!drain_pret" +
      "rained_template_matched\030\007 \001(\t\022\027\n\017inferen" +
      "ce_model\030\010 \001(\t\022\032\n\022opnilog_confidence\030\t \001" +
      "(\002\"1\n\013PayloadList\022\"\n\005items\030\001 \003(\0132\023.logan" +
      "omaly.PayloadB;\n\'org.opensearch.opniprep" +
      "rocessing.pluginB\020OpniPayloadProtob\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_loganomaly_Payload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_loganomaly_Payload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_loganomaly_Payload_descriptor,
        new java.lang.String[] { "Id", "ClusterId", "Log", "MaskedLog", "AnomalyLevel", "LogType", "DrainPretrainedTemplateMatched", "InferenceModel", "OpnilogConfidence", });
    internal_static_loganomaly_PayloadList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_loganomaly_PayloadList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_loganomaly_PayloadList_descriptor,
        new java.lang.String[] { "Items", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
